FROM alpine:latest



RUN mkdir -p home/Pictures
ADD https://images.unsplash.com/photo-1512632578888-169bbbc64f33?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D home/Pictures
ADD https://images.unsplash.com/photo-1519818187420-8e49de7adeef?q=80&w=1527&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D home/Pictures
ADD https://images.unsplash.com/photo-1590075865003-e48277faa558?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D home/Pictures

CMD [ "ls" , "home/Pictures" ]
